# Generated by Django 5.1.1 on 2024-09-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_masterunit_otherunit_show_showinfo_sourceweb_subunit_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
